name: tasbeehlite
description: "Tasbeeh Lite - A simple, lightweight app for quick Tasbeeh counting. Created by Soiad Mahedi."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  share_plus: ^11.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  audioplayers: ^6.0.0
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/tasbeeh_lite_splash_icon.png
  branding: assets/images/ic_soiadmahedi_brand_black.png
  android: true
  ios: true
  web: true
  fullscreen: true

  android_12:
    color: "#FFFFFF"
    image: assets/icon/tasbeeh_lite_splash_icon.png
    branding: assets/images/ic_soiadmahedi_brand_black.png


flutter_launcher_icons:
  android: true
  ios: true
  linux: true
  image_path: "assets/icon/tasbeehlite_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#CAF8CD"
  adaptive_icon_foreground: "assets/icon/tasbeehlite_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/tasbeeh.png
    - assets/images/tasbeeh_lite_icon.png
    - assets/images/ic_soiadmahedi_brand_black.png
    - assets/images/ic_soiadmahedi_brand_white.png
    - assets/icon/tasbeeh_lite_splash_icon.png
    - assets/sounds/click_sound.mp3
    - assets/i18n/bn.json
    - assets/i18n/en.json
    - assets/i18n/sw.json

  fonts:
    - family: LiAdorFont
      fonts:
        - asset: assets/fonts/li_ador_noirrit.ttf

    - family: NotoSansSylotiNagri
      fonts:
        - asset: assets/fonts/notosanssylotinagri.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/notonaskharabic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
